<?php

namespace CarBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCarsWithDetails()
    {
        $qb = $this->createQueryBuilder('car');
        $qb->select('car, make, model');
        $qb->join('car.make', 'make');
        $qb->join('car.model', 'model');
        return $qb->getQuery()->getResult();
    }

    public function findSingleCarWithDetailsById($id)
    {
        $qb = $this->createQueryBuilder('car');
        $qb->select('car, make, model');
        $qb->join('car.make', 'make');
        $qb->join('car.model', 'model');
        $qb->where('car.id = :id');
        $qb->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }
}
